server:
  port: 8095 # :8095은 기본값으로, 변수가 없을 경우 사용됩니다.

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://mysql-service:3306/msa-study?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
  kafka:
    consumer:
      bootstrap-servers: kafka-service:29092
      group-id: consumerGroupId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
