server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway-mvc
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: first-service
              uri: http://localhost:8081/
              predicates:
                - Path=/first-service/**
            - id: second-service
              uri: http://localhost:8082/
              predicates:
                - Path=/second-service/**
