services:
  discovery-server:
    build: ./discovery-server
    image: discovery-server:1.0.0
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - msa-net

  config-service:
    build: ./config-service
    image: config-service:1.0.0
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_started
    networks:
      - msa-net

  gateway-service:
    build: ./gateway-reactive
    image: gateway-service:1.0.0
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      discovery-server:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - msa-net

  user-service:
    build: ./msa-user-service
    image: user-service:1.0.0
    container_name: user-service
    ports:
      - "8090:8090"
    depends_on:
      discovery-server:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - msa-net

networks:
  msa-net:
    external: true
