server:
  port: 8090

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql-service:3306/msa-study?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
  security:
    user:
      name: test
      password: $2a$10$MfHrLw/sjpTqrW2Hveg9uu0WyDP3.Z4uuj9lnJdn5UJ1CLs5pnski

gateway:
  secret: gateway-secret-key

greeting:
  message: Welcome to the Simple E-commerce - 2nd.

token:
  secret: my-very-long-secret-key-1234567890123456
  expiration-time: 86400000 # 10 days

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
