server:
  port: 0

spring:
  application:
    name: discovery-client-sample

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
