server:
  port: ${SERVER_PORT:8888} # :8888은 기본값으로, 변수가 없을 경우 사용됩니다.

spring:
  application:
    name: config-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          default-label: ${CONFIG_SERVER_GIT_LABEL}

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info, busrefresh

encrypt:
  key-store:
    location: file:./config-service/apiEncryptKey.jks
    password: ${KEY_STORE_PASSWORD}
    alias: apiEncryptKey
