server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git: #default
          uri: https://github.com/Pablo730/spring-cloud-config
          default-label: main
#          username: [username]
#          password: [password]
